# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: faa04d34048965f401b834bb512c2111b3790430d33fc7bd0a05e2531bf732dd18a1dfcc6de2bda0dbee6acb10da071e907bbe063aec92e93b6e2c9aa921a017

test:
  secret_key_base: 2fbb3d470e3fcb5b2c099da4da47d71fde1ca7ac77a9822e8d0d5afd6b90b578849ac79ccfcdc554e31f3b0f756005f2a033cc04396daca9880f89179cc92f3a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
